#!/usr/bin/env python3
"""Generate the C front-end tables from the Python ones.

The renderer tables are generated by gen_tables.py for the reason given
there: transliterating a few thousand values by hand is how a voice
quietly changes. The same applies to the 403 reciter rules and the
phoneme flag table, so they are generated too. Run from anywhere after
any table change:

    python native/tools/gen_frontend_tables.py

Writes native/src/sam_parser_tables.{h,c},
native/src/sam_reciter_tables.{h,c} and
native/src/sam_cmudict_tables.{h,c}.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, 'nvda-addon', 'synthDrivers', 'sam'))

import reciter                # noqa: E402  (builds _rules / _rules2)
import reciter_tables as rct  # noqa: E402
import parser_tables as pt    # noqa: E402
import cmudict                # noqa: E402

OUT = os.path.join(ROOT, 'native', 'src')

BANNER = """/*
 * %s - GENERATED FILE, DO NOT EDIT.
 *
 * Produced by native/tools/gen_frontend_tables.py from
 * nvda-addon/synthDrivers/sam/%s. Edit the Python tables and
 * regenerate; hand-editing these numbers is how the voice changes by
 * accident.
 */
"""


def cstr(s):
    """A C string literal for s, which is ASCII but may contain " or \\."""
    out = ['"']
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '?':
            out.append('\\?')      # never let ??x form a trigraph
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            raise SystemExit('non-ASCII in rule text: %r' % s)
    out.append('"')
    return ''.join(out)


# --------------------------------------------------------------------------
# parser tables
# --------------------------------------------------------------------------

def gen_parser_tables():
    names = pt.PHONEME_NAME_TABLE
    flags = pt.PHONEME_FLAGS
    lens = pt.COMBINED_PHONEME_LENGTH_TABLE
    stress = pt.STRESS_TABLE

    if len(names) != len(flags):
        raise SystemExit('name/flag table length mismatch')
    for v in flags:
        if not (0 <= v <= 0xFFFF):
            raise SystemExit('phoneme flag %d does not fit in uint16_t' % v)
    for v in lens:
        if not (0 <= v <= 0xFFFF):
            raise SystemExit('phoneme length %d does not fit in uint16_t' % v)
    for n in names:
        if len(n) != 2:
            raise SystemExit('phoneme name %r is not two characters' % n)

    h = [BANNER % ('sam_parser_tables.h', 'parser_tables.py'), """
#ifndef SAM_PARSER_TABLES_H
#define SAM_PARSER_TABLES_H

#include <stdint.h>

#define SAM_PHONEME_NAME_COUNT   %d
#define SAM_PHONEME_LENGTH_COUNT %d
#define SAM_STRESS_COUNT         %d

/* Two characters and a NUL, so they compare with strncmp. */
extern const char     sam_phoneme_names[SAM_PHONEME_NAME_COUNT][3];
extern const uint16_t sam_phoneme_flags[SAM_PHONEME_NAME_COUNT];

/*
 * Low byte is the unstressed length, high byte the stressed one.
 *
 * This table is one entry SHORTER than the name and flag tables: Python
 * has 80 entries against 81 phonemes, so UN (80) has no length. It never
 * reaches set_phoneme_length because parser2 rewrites UN to AX N* first.
 * The count is kept separate rather than padded so a C bounds check and
 * a Python IndexError describe the same table.
 */
extern const uint16_t sam_phoneme_length_combined[SAM_PHONEME_LENGTH_COUNT];

/* "*12345678" - index into this is the stress value. */
extern const char sam_stress_chars[SAM_STRESS_COUNT + 1];

#endif /* SAM_PARSER_TABLES_H */
""" % (len(names), len(lens), len(stress))]

    c = [BANNER % ('sam_parser_tables.c', 'parser_tables.py'),
         '\n#include "sam_parser_tables.h"\n\n']

    c.append('const char sam_phoneme_names[SAM_PHONEME_NAME_COUNT][3] = {\n')
    for i in range(0, len(names), 8):
        c.append('    ' + ' '.join(cstr(n) + ',' for n in names[i:i + 8]) + '\n')
    c.append('};\n\n')

    c.append('const uint16_t sam_phoneme_flags[SAM_PHONEME_NAME_COUNT] = {\n')
    for i in range(0, len(flags), 8):
        c.append('    ' + ' '.join('0x%04X,' % v for v in flags[i:i + 8]) + '\n')
    c.append('};\n\n')

    c.append('const uint16_t sam_phoneme_length_combined'
             '[SAM_PHONEME_LENGTH_COUNT] = {\n')
    for i in range(0, len(lens), 8):
        c.append('    ' + ' '.join('0x%04X,' % v for v in lens[i:i + 8]) + '\n')
    c.append('};\n\n')

    c.append('const char sam_stress_chars[SAM_STRESS_COUNT + 1] = %s;\n'
             % cstr(''.join(stress)))

    return ''.join(h), ''.join(c)


# --------------------------------------------------------------------------
# reciter tables
# --------------------------------------------------------------------------

def gen_reciter_tables():
    # char_flags is a sparse dict in Python and every key is ASCII; a flat
    # 256-entry table gives C the same "missing means zero" behaviour that
    # char_flags.get(c, 0) gives Python.
    flags = [0] * 256
    for ch, v in rct.char_flags.items():
        if len(ch) != 1 or ord(ch) > 127:
            raise SystemExit('char_flags key %r is not a single ASCII char' % ch)
        if not (0 <= v <= 0xFF):
            raise SystemExit('char flag %d does not fit in uint8_t' % v)
        flags[ord(ch)] = v

    # Flatten the per-character rule lists into one array plus an index,
    # keeping Python's insertion order within each character: the rule
    # engine takes the first rule that matches, so the order is the
    # behaviour.
    flat = []
    offsets = [0] * 256
    counts = [0] * 256
    for ch in sorted(reciter._rules):
        rules = reciter._rules[ch]
        offsets[ord(ch)] = len(flat)
        counts[ord(ch)] = len(rules)
        flat.extend(rules)

    rules2 = reciter._rules2

    def emit_rules(name, rules):
        out = ['const sam_rule_t %s[%d] = {\n' % (name, len(rules))]
        for r in rules:
            out.append('    { %s, %s, %s, %s, %d },\n'
                       % (cstr(r.pre), cstr(r.match), cstr(r.post),
                          cstr(r.target), len(r.match)))
        out.append('};\n\n')
        return ''.join(out)

    h = [BANNER % ('sam_reciter_tables.h', 'reciter_tables.py'), """
#ifndef SAM_RECITER_TABLES_H
#define SAM_RECITER_TABLES_H

#include <stdint.h>

#define SAM_RULE_COUNT  %d
#define SAM_RULE2_COUNT %d

/*
 * One reciter rule, "xxx(yyy)zzz=foobar" already split at the brackets:
 * pre is xxx, match is yyy, post is zzz and target is the phonemes to
 * emit. Splitting here rather than at match time is the whole reason
 * this file is generated.
 */
typedef struct {
    const char   *pre;
    const char   *match;
    const char   *post;
    const char   *target;
    unsigned char match_len;
} sam_rule_t;

/* Indexed by character; entries Python left out of char_flags are 0. */
extern const uint8_t sam_char_flags[256];

/*
 * The main rule set, grouped by the first character of match. Rules for
 * character c are sam_rules[sam_rule_off[c] .. + sam_rule_cnt[c]), in
 * the order Python stores them - the engine takes the first match, so
 * that order is behaviour and not presentation.
 */
extern const sam_rule_t sam_rules[SAM_RULE_COUNT];
extern const int16_t    sam_rule_off[256];
extern const int16_t    sam_rule_cnt[256];

/* Punctuation, digits and symbols: one flat list, tried in order. */
extern const sam_rule_t sam_rules2[SAM_RULE2_COUNT];

#endif /* SAM_RECITER_TABLES_H */
""" % (len(flat), len(rules2))]

    c = [BANNER % ('sam_reciter_tables.c', 'reciter_tables.py'),
         '\n#include "sam_reciter_tables.h"\n\n']

    c.append('const uint8_t sam_char_flags[256] = {\n')
    for i in range(0, 256, 16):
        c.append('    ' + ' '.join('0x%02X,' % v for v in flags[i:i + 16]) + '\n')
    c.append('};\n\n')

    c.append(emit_rules('sam_rules', flat))
    c.append(emit_rules('sam_rules2', rules2))

    for name, values in (('sam_rule_off', offsets), ('sam_rule_cnt', counts)):
        c.append('const int16_t %s[256] = {\n' % name)
        for i in range(0, 256, 16):
            c.append('    ' + ' '.join('%4d,' % v for v in values[i:i + 16]) + '\n')
        c.append('};\n\n')

    return ''.join(h), ''.join(c)


# --------------------------------------------------------------------------
# cmudict tables
# --------------------------------------------------------------------------

def gen_cmudict_tables():
    # Sorted so the C side can binary search, and so a diff of this file
    # after a mapping change shows the change rather than a reshuffle.
    pairs = sorted(cmudict.ARPABET_TO_SAM.items())
    for arp, sam in pairs:
        if not arp.isascii() or not sam.isascii():
            raise SystemExit('non-ASCII in ARPABET map: %r -> %r' % (arp, sam))

    stress = sorted(cmudict.CMU_TO_SAM_STRESS.items())
    if [k for k, _ in stress] != ['0', '1', '2']:
        raise SystemExit('unexpected stress keys: %r' % [k for k, _ in stress])

    h = [BANNER % ('sam_cmudict_tables.h', 'cmudict.py'), """
#ifndef SAM_CMUDICT_TABLES_H
#define SAM_CMUDICT_TABLES_H

#define SAM_ARPABET_COUNT %d

/* ARPABET base phoneme to the SAM spelling of the same sound. */
typedef struct {
    const char *arpabet;
    const char *sam;
} sam_arpabet_map_t;

/* Sorted by arpabet, so a binary search and Python's dict agree. */
extern const sam_arpabet_map_t sam_arpabet_map[SAM_ARPABET_COUNT];

/*
 * CMU stress digit to the SAM stress marker, indexed by digit - '0'.
 * "" for unstressed, "4" for primary, "2" for secondary.
 */
extern const char *const sam_stress_markers[3];

#endif /* SAM_CMUDICT_TABLES_H */
""" % len(pairs)]

    c = [BANNER % ('sam_cmudict_tables.c', 'cmudict.py'),
         '\n#include "sam_cmudict_tables.h"\n\n',
         'const sam_arpabet_map_t sam_arpabet_map[SAM_ARPABET_COUNT] = {\n']
    for arp, sam in pairs:
        c.append('    { %-6s %s },\n' % (cstr(arp) + ',', cstr(sam)))
    c.append('};\n\n')

    c.append('const char *const sam_stress_markers[3] = { %s };\n'
             % ', '.join(cstr(v) for _, v in stress))

    return ''.join(h), ''.join(c)


def write(name, text):
    path = os.path.join(OUT, name)
    with open(path, 'w', encoding='ascii', newline='\n') as f:
        f.write(text)
    print('wrote %s (%d bytes)' % (path, len(text)))


def main():
    h, c = gen_parser_tables()
    write('sam_parser_tables.h', h)
    write('sam_parser_tables.c', c)

    h, c = gen_reciter_tables()
    write('sam_reciter_tables.h', h)
    write('sam_reciter_tables.c', c)

    h, c = gen_cmudict_tables()
    write('sam_cmudict_tables.h', h)
    write('sam_cmudict_tables.c', c)


if __name__ == '__main__':
    main()
